#!/usr/bin/env python3
"""Writes evidence/README.md from every run's summary.json and each
capture's own answer, so each number in this repository comes from a run
and none is typed by hand."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "evidence"
NAMES = {
    "android-emulator": "Pixel 7 emulator, Android 15",
    "android-phone": "Pixel 8 Pro, Android 17",
    "ios-simulator": "iPhone 17 Pro simulator, iOS 26.5",
    "iphone": "iPhone 15 Plus, iOS 26.6.2",
}
ORDER = ["android-emulator", "android-phone", "ios-simulator", "iphone"]
INTERRUPTION = {
    "muted": "muted", "ringtone": "a ringtone", "alarm": "an alarm", "notification": "a notification",
    "voice_call": "a voice call", "assistant": "the assistant", "navigation": "navigation",
    "media": "another app's media", "sound": "another app's sound",
}


def answer(run, name):
    p = run / f"{name}.json"
    try:
        return json.loads(p.read_text()) if p.exists() else None
    except ValueError:
        return None


def heard(a):
    """The sounds longer than 0.2 s, in order, as the timeline gives them."""
    if not a:
        return "—"
    sounds = [s for s in a.get("timeline") or [] if s["sound"] and s["to"] - s["from"] > 2e8]
    if not sounds:
        return "silence"
    return ", then ".join(
        (f"{s['hz']:.0f} Hz" if s.get("hz") else "sound") + f" for {(s['to'] - s['from']) / 1e9:.1f} s"
        for s in sounds)


def tone_heard(a, hz=440):
    """Where the app's tone was heard, and how many other sounds came between
    — a ringtone's or an alarm's pitches, which listed one by one bury it."""
    if not a:
        return "—"
    sounds = [x for x in a.get("timeline") or [] if x["sound"] and x["to"] - x["from"] > 2e8]
    tone = [x for x in sounds if x.get("hz") and abs(x["hz"] - hz) <= max(5, 0.02 * hz)]
    others = len(sounds) - len(tone)
    spans = ", ".join(f"{x['from'] / 1e9:.1f}–{x['to'] / 1e9:.1f} s" for x in tone) or "nowhere"
    return f"{hz} Hz at {spans}" + (f", and {others} other sound{'s' if others > 1 else ''} between" if others else "")


def cut(a):
    if not a:
        return "—"
    items = [c for c in a.get("interruptions") or [] if c["to"] - c["from"] >= 2.5e8 or c.get("open")]
    if not items:
        return "nothing"
    out = []
    for c in items:
        name = INTERRUPTION.get(c["kind"], c["kind"])
        if c["kind"] == "muted" and c.get("reason") == "call":
            name = "muted for a call"
        out.append(f"{name} {c['from'] / 1e9:.1f}–{c['to'] / 1e9:.1f} s")
    return "; ".join(out)


def level(a):
    if not a:
        return "—"
    sounds = [s for s in a.get("timeline") or [] if s["sound"] and s["to"] - s["from"] > 3e8]
    return f"{sounds[0]['level']:.1f} dBFS" if sounds else "silence"


def link(run, name, label):
    return f"[{label}]({run.name}/{name})" if (run / name).exists() else None


runs = sorted(((p, json.loads((p / "summary.json").read_text()))
               for p in EVIDENCE.iterdir() if (p / "summary.json").exists()),
              key=lambda rs: (ORDER.index(rs[1]["device"]) if rs[1]["device"] in ORDER else 9, rs[0].name))

lines = ["# Evidence", "",
         "Every run behind this repository's numbers, generated by `scripts/summarize.py` from each run's",
         "`summary.json` and each capture's own answer. Each run folder holds a transcript of every command",
         "with what it printed, the WAVs, each stop's answer as JSON, a drawing of each, and the test reports.",
         ""]

emulators = [(r, s) for r, s in runs if s["device"] == "android-emulator"]
if emulators:
    lines += ["## On an emulator: heard", "",
              "| Run | Act 1: silence | Act 2: the sequence | Act 3: tests | Act 4: the tone by volume | Act 5: a call | Act 5: an alarm |",
              "| --- | --- | --- | --- | --- | --- | --- |"]
    for run, s in emulators:
        vols = " · ".join(f"{v}: {level(answer(run, f'act4-volume-{v}'))}" for v in (15, 5, 1, 0))
        call, alarm = answer(run, "act5-call"), answer(run, "act5-alarm")
        lines.append(
            f"| [{run.name}]({run.name}/transcript.md) | {heard(answer(run, 'act1-silence'))} "
            f"| {heard(answer(run, 'act2-sequence'))} "
            f"| heard: {s['act3']['heard']}; wrong: {s['act3']['wrong']} "
            f"| {vols} | heard {tone_heard(call)}; interrupted: {cut(call)} "
            f"| heard {tone_heard(alarm)}; interrupted: {cut(alarm)} |")
    lines.append("")

phones = [(r, s) for r, s in runs if s["device"] != "android-emulator"]
if phones:
    lines += ["## On phones and iOS", "",
              "| Run | Device | What it recorded |", "| --- | --- | --- |"]
    for run, s in phones:
        if s.get("refused"):
            what = f"refused: {s['refused'].strip().splitlines()[-1].removeprefix('error: ')}"
        else:
            what = f"an alarm over the tone — interrupted: {cut(answer(run, 'act5-alarm'))}; no sound, since a phone's is not captured"
        lines.append(f"| [{run.name}]({run.name}/transcript.md) | {NAMES.get(s['device'], s['device'])} | {what} |")
    lines.append("")

lines += ["## The drawings", ""]
for run, s in runs:
    svgs = sorted(run.glob("*.svg"))
    if not svgs:
        continue
    lines += [f"### {run.name}", ""]
    lines += [f"![{p.stem}]({run.name}/{p.name})" for p in svgs]
    lines.append("")

lines += ["## Files", ""]
for run, s in runs:
    files = [link(run, "transcript.md", "transcript"), link(run, "report-heard/index.html", "heard report"),
             link(run, "report-wrong/index.html", "wrong report"), link(run, "summary.json", "summary")]
    files += [link(run, p.name, p.stem) for p in sorted(run.glob("*.wav"))]
    lines.append(f"- **{run.name}** ({NAMES.get(s['device'], s['device'])}): " + ", ".join(f for f in files if f))
lines.append("")

(EVIDENCE / "README.md").write_text("\n".join(lines))
print(f"wrote evidence/README.md from {len(runs)} runs")
